apiVersion: v1
kind: ConfigMap
metadata:
  name: alerting-rules
data:
{{- range $path, $bytes := .Files.Glob "rules/monitoring/*" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
