deployment:
  annotations: {}

gitRepo:
  url: ""
  branch: ""
helmChartPath: ""
helmReleaseName: ""
helmReleaseNamespace: default
helmExtraValuesFiles: []

webhook:
  image:
    repository: blesswinsamuel/docker-helm
    tag: v1.0.0
  env: []
  envFromSecret: []

secretName: helm-ops

scripts:
  predeploy: ''
