{
 "title": "Postgres",
 "description": "Performance metrics for Postgres",
 "tags": [ "postgres" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(pg_up, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job=~\"$job\"},instance)"
   },
   {
    "name": "db",
    "label": "db",
    "query": "label_values(pg_stat_database_tup_fetched{instance=~\"$instance\",datname!~\"template.*|postgres\"},datname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_returned{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_deleted{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_alloc",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_backend_fsync",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_backend{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_clean{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_clean",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_checkpoint",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_blks_hit{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) / (sum by (datname)(rate(pg_stat_database_blks_hit{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) + sum by (datname)(rate(pg_stat_database_blks_read{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{datname}} - cache hit rate"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"$db\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{datname}} - {{__name__}}"
    }
   ]
  }
 ]
}