package certmanagerio


// name of the Azure environment (default AzurePublicCloud).
type ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment string

const (
	// AzurePublicCloud.
	ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment_AZURE_PUBLIC_CLOUD ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment = "AZURE_PUBLIC_CLOUD"
	// AzureChinaCloud.
	ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment_AZURE_CHINA_CLOUD ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment = "AZURE_CHINA_CLOUD"
	// AzureGermanCloud.
	ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment_AZURE_GERMAN_CLOUD ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment = "AZURE_GERMAN_CLOUD"
	// AzureUSGovernmentCloud.
	ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment_AZURE_US_GOVERNMENT_CLOUD ClusterIssuerSpecAcmeSolversDns01AzureDnsEnvironment = "AZURE_US_GOVERNMENT_CLOUD"
)

