{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "goatcounter.serviceAccountName" . }}
  labels:
{{ include "goatcounter.labels" . | indent 4 }}
{{- end -}}
