# https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: "v1.8.0"
  targetNamespace: cert-manager
  set:
    installCRDs: "true"
