# https://github.com/DopplerHQ/kubernetes-operator/pull/9/files
# https://github.com/DopplerHQ/helm-charts
---
apiVersion: v1
kind: Namespace
metadata:
  name: doppler-operator-system
  labels:
    control-plane: controller-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: doppler-kubernetes-operator
  namespace: doppler-operator-system
spec:
  repo: https://blesswinsamuel.github.io/helm-charts
  chart: doppler-kubernetes-operator
  version: "1.0.1"
  targetNamespace: doppler-operator-system
  set:
    installCRDs: "true"
