# https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: "0.7.2"
  targetNamespace: external-secrets
  set:
    installCRDs: "true"
