databases:
  postgres:
    helm:
      repo: https://charts.bitnami.com/bitnami
      chart: postgresql
      version: "12.9.0"
    image:
      # not straightforward to upgrade to postgres 15
      # 2023-03-18 16:30:09.021 GMT [1] FATAL:  database files are incompatible with server
      # 2023-03-18 16:30:09.021 GMT [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 15.2.
      repository: bitnami/postgresql
      tag: 15.4.0
    database: null
    username: null

  redis:
    helm:
      repo: https://charts.bitnami.com/bitnami
      chart: redis
      version: "17.16.0"

auth:
  authelia:
    helm:
      repo: https://charts.authelia.com
      chart: authelia
      version: "0.8.57"
    ingress:
      subDomain: authelia
    ldap:
      usersFilter: "(&({username_attribute}={input})(!({username_attribute}=admin))(objectClass=person))"
      groupsFilter: "(member={dn})"
      displayNameAttribute: displayName
      mailAttribute: mail
    database:
      postgres:
        host: "postgres.database.svc.cluster.local"
      redis:
        host: "redis-master.database.svc.cluster.local"

  lldap:
    image:
      repository: ghcr.io/lldap/lldap
      tag: v0.4.3-alpine

  traefikForwardAuth:
    helm:
      repo: https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: "2.2.2"
    image:
      repository: thomseddon/traefik-forward-auth
      tag: 2.2.0-arm
    ingress:
      subDomain: "auth"
    whilelist: "" # email address

monitoring:
  vector:
    helm:
      repo: https://helm.vector.dev
      chart: vector
      version: "0.24.1"
    syslogServer:
      enabled: false
    ingress:
      enabled: false
      subDomain: vector

system:
  kubeGitOps:
    gitSync:
      image:
        repository: blesswinsamuel/git-sync
        tag: v3.6.0
    webhook:
      image:
        repository: blesswinsamuel/docker-helm
        tag: v1.0.1
    gitRepo:
      url: ""
      branch: ""
    kapp:
      appName: ""
      directory: ""
      namespace: ""
