[tool.poetry]
name = "grafana-dashboards"
version = "0.1.0"
description = ""
authors = ["Blesswin Samuel"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "6.0"
requests = "2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
