name: Test
on:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Set up cache
        id: cache-charts-dashboards-alerts
        uses: actions/cache@v3
        env:
          cache-name: cache-charts-dashboards-alerts
        with:
          path: ./cache
          key: cache-${{ env.cache-name }}
      - name: go build
        run: |
          CGO_ENABLED=0 go build ./...
      # - name: run stack commands
      #   run: |
      #     /tmp/bless-stack xxx
